module.exports = {
  rules: {
    semi: ['error', 'always'],
    quotes: 0,
    indent: 0,
    camelcase: 0,
    'max-len': ['error', 120],
    'brace-style': 0,
    'comma-spacing': 0,
    'dot-notation': 0,
    'func-call-spacing': 0,
    'keyword-spacing': 0,
    'lines-between-class-members': 0,
    'space-before-function-paren': 0,
    'class-methods-use-this': 0,
    //
    'no-console': 0,
    'no-array-constructor': 0,
    'no-dupe-class-members': 0,
    'no-empty-function': 0,
    'no-extra-parens': 0,
    'no-extra-semi': 0,
    'no-implied-eval': 0,
    'no-magic-numbers': 0,
    'no-throw-literal': 0,
    'no-unused-expressions': 0,
    'no-unused-vars': 0,
    'no-use-before-define': ['error', { functions: false }],
    'no-underscore-dangle': 0,
    'no-useless-constructor': 0,
    //
    'import/prefer-default-export': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-unresolved': ['error', { ignore: ['@'] }],
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
        mjs: 'never',
      },
    ],
  },
};
